module.exports = {
  phrases: [
    "The possibilities are endless.",
    "Crawling towards agnostic enlightenment",
    "Can the dream dream the dreamer",
    "Burn your money.",
    "Both sides of the sky.",
    "The brandy of the damned",
    "The primal orgasm",
    "Money is only an extreme and specialised type of ritual.",
    "The higher you fly, the smaller you appear to those below.",
    "The pale fox.",
    "Just connect",
    "The pursuit of control",
    "Orderly chaos.",
    "Natural law and disorder",
    "Innit!",
    "The shinning ones",
    "It’s right to fight for what you want, for all that you believe.",
    "Thunderbirds are go!",
    "Grot",
    "Kipple",
    "Are you Sirius ?",
    "Only apparently real",
    "Critical path analysis",
    "Random deaths and custard",
    "I’m the only real anarchist here",
    "See how they run",
    "I am who I am",
    "Everything you know is wrong",
    "Mosbunall",
    "Specialisation is for insects"
  ]
};
