module.exports = {
  company: [
    "Cage-Brand Steam Generators",
    "Pickem's Enterprise Loans",
    "Pickem's Enterprise Loans",
    "Pickem's Enterprise Loans",
    "Pickem's Enterprise Loans",
    "Anise Sisters Security Wire",
    "Anise Sisters Security Wire",
    "Anise Sisters Security Wire",
    "Gasman Spice & Soap",
    "Prospective Telecoms",
    "Prospective Telecoms",
    "Prospective Telecoms",
    "The Lady's Sugar and Coffeehouse",
    "The Lady's Sugar and Coffeehouse",
    "The Lady's Sugar and Coffeehouse",
    "Yesser's Wool and Meat",
    "Yesser's Wool and Meat",
    "Secure Properties and Jails",
    "Secure Properties and Jails",
    "Consolidated Bookmakers",
    "Consolidated Bookmakers",
    "Consolidated Bookmakers",
    "Commercial Voice Printed Press",
    "Commercial Voice Printed Press",
    "Commercial Voice Printed Press",
    "Commercial Voice Printed Press",
    "Gallow, Sniff, & Pine Medical Research",
    "Gallow, Sniff, & Pine Medical Research",
    "Gallow, Sniff, & Pine Medical Research",
    "Claymore Bank & Private Military",
    "Claymore Bank & Private Military",
    "Claymore Bank & Private Military",
    "Claymore Bank & Private Military",
    "Broken Compass Offshore Acquisitions",
    "Broken Compass Offshore Acquisitions",
    "Broken Compass Offshore Acquisitions",
    "Broken Compass Offshore Acquisitions",
    "Baker Arms & Munitions",
    "Baker Arms & Munitions",
    "Cohen Mass Nutrition Solutions",
    "Cohen Mass Nutrition Solutions",
    "Cohen Mass Nutrition Solutions",
    "Footman Stills Spirits & Tonics",
    "Footman Stills Spirits & Tonics",
    "Footman Stills Spirits & Tonics",
    "Footman Stills Spirits & Tonics",
    "Braker's Streetlamp and Halberd",
    "Braker's Streetlamp and Halberd",
    "Braker's Streetlamp and Halberd",
    "Braker's Streetlamp and Halberd",
    "Black Horse Hospitals and Asylums",
    "Black Horse Hospitals and Asylums",
    "Black Horse Hospitals and Asylums",
    "Black Horse Hospitals and Asylums",
    "Bastio-Goldish Coal, Oil, and Ore",
    "Bastio-Goldish Coal, Oil, and Ore",
    "Bastio-Goldish Coal, Oil, and Ore",
    "Confectioner's Village Foods & Homes",
    "Confectioner's Village Foods & Homes",
    "Confectioner's Village Foods & Homes",
    "Red Ghost Roads & Carriages",
    "Red Ghost Roads & Carriages",
    "Freeman Brewers & Bakers",
    "Freeman Brewers & Bakers",
    "Drake Ships & Sails",
    "Drake Ships & Sails",
    "Drake Ships & Sails",
    "Shooman Boots & Tonics",
    "Shooman Boots & Tonics",
    "Shooman Boots & Tonics",
    "Bates' Smoke Farms",
    "Bates' Smoke Farms",
    "Bates' Smoke Farms",
    "Bates' Smoke Farms",
    "Bates' Smoke Farms",
    "Great Underground Disposal Company",
    "Great Underground Disposal Company",
    "Clock's Shippage & Canals",
    "Clock's Shippage & Canals",
    "Clock's Shippage & Canals",
    "Hightower Hats & Canes",
    "Hightower Hats & Canes",
    "Hightower Hats & Canes",
    "Territorial Tea & Wine",
    "Territorial Tea & Wine",
    "Outlander's Exotic Down & Fur",
    "Outlander's Exotic Down & Fur",
    "Furrupp's Brick & Mortar",
    "Furrupp's Brick & Mortar",
    "Furrupp's Brick & Mortar",
    "Bitter & Snatch Jewellery",
    "Werner's Industrial Machinery",
    "Werner's Industrial Machinery",
    "Silvermountain Private Security",
    "Silvermountain Private Security",
    "Aria Mines",
    "Aria Mines",
    "Miracle Factory Ice & Salt",
    "Miracle Factory Ice & Salt",
    "Metropolitan Tramway",
    "Metropolitan Tramway",
    "Sunfair Gold Holdings"
  ]
};
