module.exports = {
  manner: [
    "Attractive Dullard",
    "Big Fat Glutton",
    "Big Fat Glutton",
    "Big Fat Glutton",
    "Big Fat Glutton",
    "Beaky Bore Best",
    "Beaky Bore Best",
    "Beaky Bore Best",
    "Creaky Elder",
    "Creaky Elder",
    "Childlike",
    "Childlike",
    "Dashing Young Gun",
    "Dashing Young Gun",
    "Dashing Young Gun",
    "Ethereal Beauty",
    "Ethereal Beauty",
    "Fails at Flirtatious",
    "Fails at Flirtatious",
    "Flamboyant Charmer",
    "Flamboyant Charmer",
    "Flamboyant Charmer",
    "Great Speaker",
    "Great Speaker",
    "Greasy Toad",
    "Greasy Toad",
    "Greasy Toad",
    "Gentle Giant",
    "Gentle Giant",
    "Gentle Giant",
    "Hulking Brute",
    "Hulking Brute",
    "Hulking Brute",
    "Hunchback",
    "Harmless Dope",
    "Harmless Dope",
    "Harmless Dope",
    "Harmless Dope",
    "Harmless Dope",
    "Intensely Creepy",
    "Intensely Creepy",
    "Ill-Coloured and Thin",
    "Ill-Coloured and Thin",
    "Jolly and Fat",
    "Jolly and Fat",
    "Jolly and Fat",
    "Loads of Jewellery",
    "Loads of Jewellery",
    "Loads of Jewellery",
    "Lots of Scars",
    "Lots of Scars",
    "Lots of Scars",
    "Lots of Scars",
    "No Nose",
    "No Nose",
    "No Nose",
    "Nice but Dim",
    "Nice but Dim",
    "Nice but Dim",
    "Naive Teenager",
    "Naive Teenager",
    "Naive Teenager",
    "Old Sleaze",
    "Old Sleaze",
    "Pig-Faced",
    "Pig-Faced",
    "Plucky Little Thing",
    "Plucky Little Thing",
    "Plucky Little Thing",
    "Powdered Wig",
    "Powdered Wig",
    "Powdered Wig",
    "Powdered Wig",
    "Quite Ugly",
    "Quite Ugly",
    "Quite Ugly",
    "Quite Ugly",
    "Rough as a Dog",
    "Rough as a Dog",
    "Stocky Grunter",
    "Stocky Grunter",
    "Stocky Grunter",
    "Stunted Growth",
    "Stunted Growth",
    "Straight-Laced",
    "Straight-Laced",
    "Towering Klutz",
    "Towering Klutz",
    "Towering Klutz",
    "Unwashed Slob",
    "Vapid Fashionista",
    "Vapid Fashionista",
    "Vapid Fashionista",
    "Very Long Hair",
    "Very Long Hair",
    "Very Long Hair",
    "Well-Bred Snob",
    "Well-Bred Snob",
    "Waif",
    "Waif",
    "Weird Head"
  ],

  connection: [
    "Aunt/Uncle",
    "Sibling",
    "Sibling",
    "Sibling",
    "Sibling",
    "Friend",
    "Friend",
    "Friend",
    "Owes Money",
    "Owes Money",
    "Old Friend",
    "Old Friend",
    "Common ancestry",
    "Common ancestry",
    "Common ancestry",
    "Platonic Love",
    "Platonic Love",
    "Admiration",
    "Admiration",
    "Parent",
    "Parent",
    "Parent",
    "Owed Money",
    "Owed Money",
    "Acquaintance",
    "Acquaintance",
    "Acquaintance",
    "Common Benefactor",
    "Common Benefactor",
    "Common Benefactor",
    "Hatred",
    "Hatred",
    "Hatred",
    "Irritation",
    "Twin",
    "Twin",
    "Twin",
    "Twin",
    "Twin",
    "Spouse",
    "Spouse",
    "Guardian",
    "Guardian",
    "Lover",
    "Lover",
    "Lover",
    "Mentor",
    "Mentor",
    "Mentor",
    "Abuser",
    "Abuser",
    "Abuser",
    "Abuser",
    "Lust",
    "Lust",
    "Lust",
    "Distaste",
    "Distaste",
    "Distaste",
    "House-Share",
    "House-Share",
    "House-Share",
    "Former Colleagues",
    "Former Colleagues",
    "School Friends",
    "School Friends",
    "Adopted Parent",
    "Adopted Parent",
    "Adopted Parent",
    "Unrequited Love",
    "Unrequited Love",
    "Unrequited Love",
    "Unrequited Love",
    "Planning Murder",
    "Planning Murder",
    "Planning Murder",
    "Planning Murder",
    "Knows Secret",
    "Knows Secret",
    "One Night Stand",
    "One Night Stand",
    "One Night Stand",
    "Rivals",
    "Rivals",
    "Backhand Deal",
    "Backhand Deal",
    "Criminal Enterprise",
    "Criminal Enterprise",
    "Criminal Enterprise",
    "Shared Trauma",
    "Jealousy",
    "Jealousy",
    "Jealousy",
    "Violent Hate",
    "Violent Hate",
    "Violent Hate",
    "Engaged",
    "Engaged",
    "Protector",
    "Protector",
    "Playful Rivalry"
  ]
};
