module.exports = {
  occupation: [
    "Actor",
    "Barge Pilot",
    "Barge Pilot",
    "Barge Pilot",
    "Barge Pilot",
    "Butler",
    "Butler",
    "Butler",
    "Coffee House Host",
    "Coal Miner",
    "Coal Miner",
    "Coal Miner",
    "Dog Breeder",
    "Dog Breeder",
    "Dog Breeder",
    "Engine Cleaner",
    "Engine Cleaner",
    "Fist Fighter",
    "Fist Fighter",
    "Fishmonger",
    "Fishmonger",
    "Fishmonger",
    "Gull-Catcher",
    "Gull-Catcher",
    "Glue maker",
    "Glue maker",
    "Gunsmith",
    "Gunsmith",
    "Gunsmith",
    "Gin-Maker",
    "Gin-Maker",
    "Gin-Maker",
    "Gin-Maker",
    "Hog-Slaughterer",
    "Hog-Slaughterer",
    "Hog-Slaughterer",
    "Hog-Slaughterer",
    "Ivory Worker",
    "Ivory Worker",
    "Jeweler",
    "Jeweler",
    "Lower-Politician",
    "Lower-Politician",
    "Life Servant",
    "Life Servant",
    "Life Servant",
    "Lamp-Lighter",
    "Lamp-Lighter",
    "Lamp-Lighter",
    "Lesser-Noble",
    "Lesser-Noble",
    "Lesser-Noble",
    "Lesser-Noble",
    "Mercenary",
    "Mercenary",
    "Mercenary",
    "Newspaper Vendor",
    "Newspaper Vendor",
    "Newspaper Vendor",
    "Octopus-Catcher",
    "Octopus-Catcher",
    "Octopus-Catcher",
    "Oyster Seller",
    "Oyster Seller",
    "Perfumer",
    "Perfumer",
    "Professor",
    "Professor",
    "Professor",
    "Prison Guard",
    "Prison Guard",
    "Prison Guard",
    "Prison Guard",
    "Pie-Smith",
    "Pie-Smith",
    "Pie-Smith",
    "Pie-Smith",
    "Road Sweeper",
    "Road Sweeper",
    "Salt Farmer",
    "Salt Farmer",
    "Salt Farmer",
    "Sweet-Maker",
    "Sweet-Maker",
    "Trinket-Merchant",
    "Trinket-Merchant",
    "Tax Collector",
    "Tax Collector",
    "Tax Collector",
    "Tunnel Digger",
    "Whaler",
    "Whaler",
    "Whaler",
    "Watchmaker",
    "Watchmaker",
    "Watchmaker",
    "Watchman",
    "Watchman",
    "Writer",
    "Writer",
    "Wigmaker"
  ],

  capability: [
    "Anal-Retentive",
    "Boringly Dependable",
    "Boringly Dependable",
    "Boringly Dependable",
    "Boringly Dependable",
    "Best in the City",
    "Best in the City",
    "Best in the City",
    "Cheap and Dirty",
    "Charming and Oily",
    "Charming and Oily",
    "Charming and Oily",
    "Dabbler",
    "Dabbler",
    "Dabbler",
    "Expensive and Flashy",
    "Expensive and Flashy",
    "Fair and Down to Earth",
    "Fair and Down to Earth",
    "Filthy but very cheap",
    "Filthy but very cheap",
    "Filthy but very cheap",
    "Great, but hated for it",
    "Great, but hated for it",
    "Good but Annoying",
    "Good but Annoying",
    "Highly Artistic",
    "Highly Artistic",
    "Highly Artistic",
    "Hardly trained",
    "Hardly trained",
    "Hardly trained",
    "Hardly trained",
    "Inherited Family Trade",
    "Inherited Family Trade",
    "Inherited Family Trade",
    "Inherited Family Trade",
    "Interested in new career",
    "Interested in new career",
    "Imposter",
    "Imposter",
    "Jealous of Better Rival",
    "Jealous of Better Rival",
    "Learning, still.",
    "Learning, still.",
    "Learning, still.",
    "Loves the job",
    "Loves the job",
    "Loves the job",
    "Lazy and Greedy",
    "Lazy and Greedy",
    "Lazy and Greedy",
    "Lazy and Greedy",
    "Money-Grabbing",
    "Money-Grabbing",
    "Money-Grabbing",
    "Moral, but not that good",
    "Moral, but not that good",
    "Moral, but not that good",
    "Only serves friends",
    "Only serves friends",
    "Only serves friends",
    "Old-Master-Trained",
    "Old-Master-Trained",
    "Perfectionist",
    "Perfectionist",
    "Paragon of the Job",
    "Paragon of the Job",
    "Paragon of the Job",
    "Poor from bad business",
    "Poor from bad business",
    "Poor from bad business",
    "Poor from bad business",
    "Retired from Injury",
    "Retired from Injury",
    "Retired from Injury",
    "Retired from Injury",
    "Ruthless",
    "Ruthless",
    "Sworn into Profession",
    "Sworn into Profession",
    "Sworn into Profession",
    "Silently dutiful",
    "Silently dutiful",
    "Trained from Birth",
    "Trained from Birth",
    "Trapped in Job",
    "Trapped in Job",
    "Trapped in Job",
    "Uncaring",
    "Unreliable Genius",
    "Unreliable Genius",
    "Unreliable Genius",
    "Wedded into Career",
    "Wedded into Career",
    "Wedded into Career",
    "Wasted Talent",
    "Wasted Talent",
    "Warm and Friendly",
    "Warm and Friendly",
    "Wealthy with Success"
  ]
};
