module.exports = {
  whatHappened: [
    "Arrested Wrongfully for Minor Crime",
    "Arrested Rightfully for Major Crime",
    "Arrested Rightfully for Major Crime",
    "Arrested Rightfully for Major Crime",
    "Arrested Rightfully for Major Crime",
    "Became Addicted to an Exotic Drug",
    "Became Addicted to an Exotic Drug",
    "Contracted a Terrible Disease",
    "Contracted a Terrible Disease",
    "Debt Collectors are Applying Pressure",
    "Debt Collectors are Applying Pressure",
    "Died in an Uprising",
    "Died in an Uprising",
    "Died in Industrial Accident",
    "Died in Industrial Accident",
    "Found Long-Lost Relative",
    "Found Long-Lost Relative",
    "Found (new) Love",
    "Found (new) Love",
    "Found a Major Arcanum",
    "Found a Major Arcanum",
    "Found a Major Arcanum",
    "Found a Lesser Arcanum",
    "Found a Lesser Arcanum",
    "Getting (Re)Married",
    "Getting (Re)Married",
    "Joined a Star Cult",
    "Joined a Star Cult",
    "Joined a Star Cult",
    "Joined a New Revolutionary Group",
    "Joined a New Revolutionary Group",
    "Joined a New Revolutionary Group",
    "Joined a New Revolutionary Group",
    "House Collapsed",
    "House Collapsed",
    "House Collapsed",
    "House Collapsed",
    "Lost at Sea",
    "Lost at Sea",
    "Lost Everything",
    "Lost Everything",
    "Lamp-Lighter Burnt Down House",
    "Lamp-Lighter Burnt Down House",
    "Left Bastion for the Deep Country",
    "Left Bastion for the Deep Country",
    "Left Bastion for the Deep Country",
    "Left Bastion for a Lesser City",
    "Left Bastion for a Lesser City",
    "Left Bastion for a Lesser City",
    "Murdered in the Street",
    "Murdered in the Street",
    "Murdered in the Street",
    "Murdered in the Street",
    "Murdered in their Bed",
    "Murdered in their Bed",
    "Murdered in their Bed",
    "Nice person has given them some juicy work",
    "Nice person has given them some juicy work",
    "Nice person has given them some juicy work",
    "Press-Ganged into Military",
    "Press-Ganged into Military",
    "Press-Ganged into Military",
    "Rumours of Criminal Activity",
    "Rumours of Criminal Activity",
    "Rumours of Criminal Activity",
    "Rumours of personal Depravity",
    "Rumours of personal Depravity",
    "Rumours of personal Depravity",
    "Rumours of personal Depravity",
    "Saw weird things in the sky",
    "Saw weird things in the sky",
    "Saw weird things in the sky",
    "Saw weird things in the sky",
    "Saw horrible beasts in the street",
    "Saw horrible beasts in the street",
    "Saw horrible beasts in the street",
    "Saw horrible beasts in the street",
    "Saw a murder nearby",
    "Saw a murder nearby",
    "Taken up Military Service",
    "Taken up Military Service",
    "Taken up Military Service",
    "Taken in an Orphan",
    "Taken in an Orphan",
    "The Watch are harassing them",
    "The Watch are harassing them",
    "Underground Weirdos Abducted Them",
    "Underground Weirdos Abducted Them",
    "Underground Weirdos Abducted Them",
    "Vanished in a Burst of Light",
    "Wandered into Underground, now missing",
    "Wandered into Underground, now missing",
    "Wandered into Underground, now missing",
    "Won a fortune by gambling",
    "Won a fortune by gambling",
    "Won a fortune by gambling",
    "Witnessed an Abduction into the night sky",
    "Witnessed an Abduction into the night sky",
    "Went on a drinking binge",
    "Went on a drinking binge",
    "Recklessly leapt into a Doomed Romance"
  ]
};
