module.exports = {
  town: ["the #townType# of #townName#"],
  townName: [
    "#townBaseName#",
    "#townBaseName#",
    "#townPrefix# #townBaseName#",
    "#townPrefix# #townBaseName#",
    "#townBaseName##townSuffix#",
    "#townPrefix# #townBaseName##townSuffix#"
  ],
  townBaseName: ["#shortNamePart.capitalize##townNameEnd#"],
  townType: [
    "town",
    "village",
    "hamlet",
    "settlement",
    "municipality",
    "borough",
    "encampment",
    "township"
  ],
  townPrefix: [
    "Little",
    "Upper",
    "Low",
    "Lower",
    "Mid",
    "Middle",
    "Nether",
    "Greater",
    "Great",
    "Stoke",
    "Earl",
    "Prince",
    "East",
    "West",
    "North",
    "South",
    "Saint",
    "Much",
    "New",
    "St."
  ],
  townSuffix: [
    "-on-the-Wold",
    "-by-the-Water",
    "-cum-#townBaseName#",
    "-next-the-Sea",
    "-by-#townBaseName#",
    "-in-the-Marsh",
    "-in-#townBaseName#",
    "-on-#townBaseName#",
    "-de-la-#townBaseName.capitalize#",
    "-super-#townBaseName.capitalize#",
    "-le-#townBaseName#",
    "-under-#townBaseName.capitalize#",
    "-over-Sands",
    "-with-#townBaseName.capitalize#",
    " Heath",
    " Castle",
    " Regis",
    " #townBaseName.capitalize#",
    " St #townBaseName.capitalize#",
    " Norton",
    " Market",
    " Bridge",
    " Wells",
    " Sands",
    " Green"
  ],
  townNameEnd: [
    "ton",
    "ington",
    "don",
    "ingdon",
    "ford",
    "hill",
    "by",
    "field",
    "ester",
    "stone",
    "ston",
    "stoke",
    "sop",
    "firth",
    "worth",
    "wood",
    "borough",
    "boro",
    "born",
    "borne",
    "burgh",
    "bury",
    "ham",
    "bridge",
    "lee",
    "leigh",
    "shot",
    "over",
    "minster",
    "castle",
    "church",
    "stoke",
    "wick",
    "moor",
    "more",
    "wich",
    "wick"
  ]
};
