module.exports = [
  "abandoned quarry",
  "air-raid shelter",
  "allotment",
  "archipelago",
  "ashram",
  "beehive",
  "bird's nest",
  "boardroom",
  "bothy",
  "car port",
  "cardboard shelter",
  "cave",
  "circus",
  "clearing",
  "clump of moss",
  "cluttered hovel",
  "coal bunker",
  "condominium",
  "crossroads",
  "dead letter office",
  "den",
  "dream",
  "dwelling",
  "fatberg",
  "featureless room",
  "fjord",
  "forest",
  "forest clearing",
  "forest of moss",
  "garden centre",
  "garden shed",
  "grove of #tree.s#",
  "grove of beech trees",
  "holiday home",
  "holiday home",
  "honeymoon suite",
  "iceberg",
  "inconspicuous hole",
  "inland sea",
  "inn",
  "isthmus",
  "karaoke bar",
  "kindergarten",
  "loft extension",
  "lost property office",
  "makerspace",
  "mountain",
  "neighborhood",
  "nest",
  "night bus",
  "nuclear bunker",
  "oasis",
  "oast house",
  "palace",
  "phone accessory shop",
  "phone mast",
  "pile",
  "plaza",
  "pool",
  "proscenium arch",
  "pub",
  "rubbish tip",
  "safe-house",
  "saloon",
  "secret base",
  "shanty town",
  "spinney",
  "strip joint",
  "Taj Mahal",
  "tavern",
  "temple",
  "thicket",
  "tree",
  "treetop shack",
  "university",
  "unruly hedge",
  "volcano",
  "windtunnel"
];
