module.exports = [
  "a cave in #inPlace#",
  "a patch of moss on #onPlace#",
  "a forgotten suburb",
  "a galaxy far far away",
  "Albert Square",
  "Albion",
  "Alt Clut",
  "an empty parking lot somewhere near Andromeda",
  "an eroded range of hills",
  "Amerika",
  "Appalachia",
  "Asgard",
  "Astrakhan",
  "Atlantis",
  "Baja California",
  "Bangkok",
  "Banterbury",
  "Bastardstown, County Wexford",
  "Bedminster",
  "BBC TV Centre",
  "Bikini Bottom",
  "Blackpool",
  "British Columbia",
  "Byker Grove",
  "Camelot",
  "Cathall Estate",
  "Chapel Perilous",
  "Cockermouth",
  "Coronation Street",
  "Damanhur",
  "Dildo, Newfoundland",
  "Eboracum",
  "Elmet",
  "Faerie",
  "Fairyland",
  "\\#Festival23",
  "Foodhall Sheffield",
  "Galactic Sector ZZ9 Plural Z Alpha",
  "Gondwana",
  "Great Snoring",
  "Halfway",
  "heaven",
  "Hebden Bridge",
  "Hen Ogledd",
  "Hokkaido",
  "Honolulu",
  "Hookland",
  "Hyboria",
  "Idiotville",
  "Jumanji",
  "Kamchatka",
  "Kilkenny",
  "Leeds Castle",
  "Little Snoring",
  "Lord's Cricket Ground",
  "Lvov",
  "Mahabalipuram",
  "Mauritania",
  "Mexico City",
  "Micronesia",
  "Middle Earth",
  "Mitteleuropa",
  "Mordor",
  "Mythago Wood",
  "Nantucket",
  "Narnia",
  "never-never-land",
  "Oblivion",
  "Oompa-loompa Land",
  "Oughtibridge",
  "outer space",
  "Oz",
  "Park Hill Flats",
  "Port Circumcision, Antarctica",
  "Pratt's Bottom",
  "Saint-Louis-du-Ha! Ha!",
  "Sandy Balls",
  "Shilbottle",
  "Shitterton",
  "Siberia",
  "Sid's Café",
  "Skegness",
  "Sleepy Hollow",
  "Stalling Walling",
  "the Adirondacks",
  "the Australian Outback",
  "the centre of an Aztec pyramid",
  "Le Cœur",
  "the Bat Cave",
  "the Borysthenes",
  "the Catskills",
  "the Earth's core",
  "the edgelands",
  "the Enchanted Forest",
  "the eye of a needle",
  "the Falkland Islands",
  "the Faroe Islands",
  "the Ghobi Desert",
  "the Grand Canyon",
  "the Grand Duchy of Lithuania",
  "the head of a pin",
  "the heart of darkness",
  "the Himalayas",
  "the Indian Ocean",
  "the kingdom of Bryneich",
  "the Midwest",
  "the Mojave desert",
  "the North of England",
  "the Outer Hebrides",
  "the Pastel City",
  "the Peak District",
  "the place you least expect",
  "the right bank of the Dniester",
  "the roots of an ancient #tree# tree",
  "the salt marshes",
  "the sea of Okhotsk",
  "the Shire",
  "the Solar System",
  "the space-time continuum",
  "the TARDIS",
  "the Temples of Humankind",
  "the Thursbitch valley",
  "the tundra",
  "the Twilight Zone",
  "the Western Spiral Arm of the galaxy",
  "Thurgoland",
  "Tijuana",
  "Timbuktu",
  "Transcarpathia",
  "Transnistria",
  "Um Dafuq, Sudan",
  "Uranus, Missouri",
  "Vegas",
  "Viriconium",
  "Wagga Wagga",
  "Waterloo",
  "Westeros",
  "Woolloomooloo",
  "Xanadu",
  "Xixax",
  "your backyard",
  "your sock drawer",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#",
  "#town#"
];
