module.exports = [
  "a mountain the size of a pinhead",
  "a static caravan site in Ingoldmells",
  "Alpha Centuri",
  "Ben Nevis",
  "Betelgeuse",
  "Broke Back Mountain",
  "Burbage Moor",
  "Earthsea",
  "Everest",
  "Flesh Hovel Lane",
  "Golgafrincham",
  "Kinder Scout",
  "Lake Titicaca",
  "Lizard Point",
  "Mars",
  "Mount Buggery",
  "Mount Doom",
  "Mount Famine",
  "Naboo",
  "Neptune",
  "Nipple Peak",
  "Oceanworld",
  "Stanage Edge",
  "Stavromula Beta",
  "Tatooine",
  "the astral plane",
  "the banks of Lake Windermere",
  "the Earth",
  "the Forest of Boland Light Railway",
  "the Frogstar",
  "the head of a pin",
  "the Old Man of Coniston",
  "the Orient Express",
  "the other side of the veil",
  "the outskirts of infinity",
  "the World of Two Moons",
  "Traal",
  "Uranus",
  "Ursa Minor Beta",
  "Vogsphere",
  "Win Hill"
];
