module.exports = [
  "aisle",
  "bed-sitting room",
  "bedroom",
  "broom-cupboard",
  "catwalk",
  "cellar",
  "chapel",
  "cinema room",
  "cloister",
  "closet",
  "communal area",
  "corner",
  "corridor",
  "doorway",
  "entrance-hall",
  "entryway",
  "hallway",
  "inspection hatch",
  "kitchen",
  "landing",
  "library",
  "lobby",
  "lounge",
  "maintenance-cupboard",
  "mezzanine",
  "mirror",
  "outhouse",
  "sauna",
  "sitting room",
  "smoking room",
  "staircase",
  "stairwell",
  "study",
  "theatre",
  "vestibule",
  "window-pane",
  "window-seat",
  "withdrawing-room",
  "gym",
  "nook",
  "crawlspace",
  "attic",
  "void space"
];
