module.exports = [
  "aisle",
  "bed-sitting room",
  "bedroom",
  "broom-cupboard",
  "catwalk",
  "cellar",
  "chapel",
  "cinema room",
  "cloister",
  "closet",
  "communal area",
  "corner",
  "corridor",
  "doorway",
  "entrance-hall",
  "entryway",
  "hallway",
  "inspection hatch",
  "kitchen",
  "landing",
  "library",
  "lobby",
  "lounge",
  "maintenance-cupboard",
  "mezzanine",
  "outhouse",
  "sitting room",
  "smoking room",
  "stairs",
  "stairwell",
  "study",
  "theatre",
  "vestibule",
  "window-seat",
  "withdrawing-room"
];
