module.exports = {
  townFull: ["the #townType# of #townName#"],
  town: ["#townName#"],
  townName: [
    "#townBaseName#",
    "#townBaseName#",
    "#townBaseName#",
    "#townPrefix# #townBaseName#",
    "#townPrefix# #townBaseName#",
    "#townPrefix# #townBaseName#",
    "#townBaseName##townSuffix#",
    "#townBaseName##townSuffix#",
    "#townBaseName##townSuffix#",
    "#townPrefix# #townBaseName##townSuffix#"
  ],
  townBaseName: [
    "#shortNamePart.capitalize##townNameEnd#",
    "#shortNamePart.capitalize##townNameEnd##townNameEnd#",
    "#townNameEnd.capitalize##shortNamePart##townNameEnd#",
    "#townNameEnd.capitalize##townNameEnd##townNameEnd#"
  ],
  townType: [
    "town",
    "village",
    "hamlet",
    "settlement",
    "municipality",
    "borough",
    "encampment",
    "township"
  ],
  townPrefix: [
    "Burnt",
    "Combe",
    "Earl",
    "East",
    "Great",
    "Greater",
    "Heights of",
    "Little",
    "Low",
    "Lower",
    "King",
    "Mid",
    "Middle",
    "Much",
    "Nether",
    "New",
    "North",
    "Prince",
    "Royal",
    "Queen",
    "Saint",
    "South",
    "Stoke",
    "Stoney",
    "Upper",
    "West"
  ],
  townSuffix: [
    " #townBaseName.capitalize#",
    " Bridge",
    " Castle",
    " Clough",
    " Crags",
    " Croft",
    " Cross",
    " Dell",
    " Green",
    " Heath",
    " Heights",
    " Lock",
    " Keys",
    " Market",
    " Meadows",
    " Mill",
    " Norton",
    " Park",
    " Reach",
    " Regis",
    " Ridge",
    " Sands",
    " St #townBaseName.capitalize#",
    " Valley",
    " Wells",
    "-by-#townBaseName#",
    "-by-the-Water",
    "-cum-#townBaseName#",
    "-de-la-#townBaseName.capitalize#",
    "-in-#townBaseName#",
    "-in-the-Marsh",
    "-le-#townBaseName#",
    "-next-the-Sea",
    "-on-#townBaseName#",
    "-on-the-Wold",
    "-over-Sands",
    "-super-#townBaseName.capitalize#",
    "-under-#townBaseName.capitalize#",
    "-with-#townBaseName.capitalize#"
  ],
  townNameEnd: [
    "bank",
    "bay",
    "beach",
    "beck",
    "born",
    "borne",
    "boro",
    "borough",
    "bottom",
    "bridge",
    "burgh",
    "burn",
    "bury",
    "by",
    "castle",
    "chapel",
    "chester",
    "church",
    "cliff",
    "cliffe",
    "clough",
    "combe",
    "court",
    "crag",
    "crest",
    "croft",
    "dean",
    "dee",
    "den",
    "dene",
    "don",
    "dyke",
    "edge",
    "ester",
    "fastleigh",
    "fell",
    "field",
    "firth",
    "ford",
    "gate",
    "gill",
    "ham",
    "head",
    "hill",
    "hope",
    "house",
    "houses",
    "ing",
    "ingdon",
    "ington",
    "land",
    "law",
    "lee",
    "leigh",
    "lor",
    "lore",
    "mere",
    "mill",
    "minster",
    "moor",
    "more",
    "moss",
    "mouth",
    "over",
    "peak",
    "pen",
    "pike",
    "pool",
    "ridge",
    "rill",
    "sea",
    "seat",
    "set",
    "sett",
    "shed",
    "shot",
    "side",
    "slate",
    "sleight",
    "sop",
    "stock",
    "stoke",
    "stoke",
    "ston",
    "stone",
    "thorpe",
    "thwaite",
    "tree",
    "try",
    "ton",
    "vale",
    "view",
    "wate",
    "well",
    "white",
    "wich",
    "wick",
    "wight",
    "wit",
    "wold",
    "wood",
    "worth"
  ]
};

// TODO: beginnings of names:
