module.exports = {
  followerAction: ["#verb# #object#", "#pilgrimage#", "#pilgrimage#"],
  pilgrimage: [
    "travel with #deityName#'s #role# to #pilgrimageSite#",
    "make a pilgrimage to #pilgrimageSite# and #quest#",
    "go on a quest to #pilgrimageSite# and #quest#",
    "ride #animal.a# to #pilgrimageSite#",
    "travel to #pilgrimageSite# by #vehicle# and #quest#"
  ],
  pilgrimageSite: [
    "#dwelling.a# #qualifiedPlace#",
    "the nearest #dwelling#",
    "a thousand-year-old #tree# tree",
    "#unqualifiedPlace#",
    "your #relation#'s #dwelling#",
    "#unqualifiedPlace# and back"
  ],
  quest: [
    "bring back #nounToPluralise.a#",
    "capture #bird.a#. Kiss it, cuddle it, and then set it free",
    "leave your #bodyPart# there",
    "sacrifice #animal.a#",
    "observe the world #adverb#",
    "meditate upon #nounToPluralise.a#",
    "spread the good news about #nounNotToPluralise#",
    "teach the locals how to really appreciate #deityDomain#"
  ],
  verb: [
    "ignore",
    "immanentise",
    "immanentize",
    "bow to",
    "destroy",
    "exalt",
    "consider",
    "relinquish",
    "respect",
    "return to",
    "explain",
    "worship",
    "improve",
    "warn the world about",
    "#followerAction# and #verb#",
    "abase yourself before",
    "become #role# of",
    "imagine you are",
    "devote your life to",
    "give #nounNotToPluralise# to",
    "heap #nounToPluralise.s# upon",
    "humiliate yourself for",
    "kiss the #role# of",
    "live the rest of your life as the #role# of",
    "make your way directly to",
    "obey the #role# of",
    "prostrate yourself before",
    "sacrifice your #anyNoun# to",
    "soil yourself with",
    "tell me more about",
    "tell the #role# about",
    "befoul yourself before the image of",
    "become the #adjective# promoter of",
    "save the #spiritAnimal.s#. And also save"
  ],

  object: [
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "yourself and #specifier# #nounToPluralise.s#"
  ],
  specifier: [
    "#specifier# #nounToPluralise#'s",
    "#nounToPluralise.a#'s #adjective#",
    "#nounNotToPluralise#'s #adjective#",
    "some",
    "the",
    "the",
    "your",
    "your #adjective#",
    "your #adjective#",
    "your #relation#'s",
    "the #adjective#",
    "the #adjective#",
    "the #relation#'s"
  ],
  relation: [
    "beloved",
    "boss",
    "colleague",
    "conscience",
    "elderly aunt",
    "enemy",
    "familiar",
    "father",
    "instinct",
    "mother",
    "neighbour",
    "pet",
    "sacred place",
    "secret crush",
    "shrine",
    "spouse",
    "tortoise",
    "totem"
  ]
};
