const corpora = require("corpora-project");
const settings = corpora
  .getFile("archetypes", "setting")
  .settings.reduce(
    (allSettings, currentSetting) =>
      allSettings.concat(currentSetting.synonyms.concat([currentSetting.name])),
    []
  );

const venues = corpora
  .getFile("geography", "venues")
  .categories.reduce(
    (allVenues, currentCategory) =>
      allVenues.concat(
        currentCategory.categories.map(category =>
          category.name.replace(/\(.*\)/, "").replace(/.* \/ (.*)/, "$1")
        )
      ),
    []
  );

const worshipPlace = [
  "abbey",
  "altar",
  "basilica",
  "cathedral",
  "cemetery",
  "chapel",
  "church",
  "graveyard",
  "hermitage",
  "maypole",
  "monastery",
  "nunnery",
  "pyramid",
  "roadside shrine",
  "shrine",
  "synagogue",
  "tabernacle",
  "temple"
];

const dwelling = [
  "abandoned quarry",
  "air-raid shelter",
  "allotment",
  "archipelago",
  "ashram",
  "beehive",
  "bird's nest",
  "boardroom",
  "bothy",
  "car port",
  "cardboard shelter",
  "cave",
  "circus",
  "clearing",
  "clump of moss",
  "cluttered hovel",
  "coal bunker",
  "condominium",
  "dead letter office",
  "den",
  "dream",
  "dwelling",
  "fjord",
  "garden centre",
  "grove of beech trees",
  "holiday home",
  "holiday home",
  "honeymoon suite",
  "iceberg",
  "inconspicuous hole",
  "inland sea",
  "inn",
  "isthmus",
  "karaoke bar",
  "kindergarten",
  "loft extension",
  "lost property office",
  "makerspace",
  "mezzanine",
  "mountain",
  "neighborhood",
  "nest",
  "nuclear bunker",
  "oasis",
  "oast house",
  "palace",
  "phone accessory shop",
  "phone mast",
  "pile",
  "plaza",
  "proscenium arch",
  "pub",
  "rubbish tip",
  "safe-house",
  "saloon",
  "secret base",
  "shanty town",
  "strip joint",
  "Taj Mahal",
  "tavern",
  "temple",
  "thicket",
  "tree",
  "treetop shack",
  "university",
  "unruly hedge",
  "volcano",
  "windtunnel"
].concat(settings, venues, worshipPlace);

const inPlace = [
  "a cave in #inPlace#",
  "a forgotten suburb",
  "a galaxy far far away",
  "Albert Square",
  "Albion",
  "an empty parking lot somewhere near Andromeda",
  "an eroded range of hills",
  "Asgard",
  "Atlantis",
  "Banterbury",
  "BBC TV Centre",
  "Bikini Bottom",
  "Blackpool",
  "Camelot",
  "Cathall Estate",
  "Faerie",
  "Fairyland",
  "Galactic Sector ZZ9 Plural Z Alpha",
  "Gondwana",
  "Halfway",
  "heaven",
  "Honolulu",
  "Hookland",
  "Hyboria",
  "Jumanji",
  "Lord's Cricket Ground",
  "Mahabalipuram",
  "Mauritania",
  "Middle Earth",
  "Mordor",
  "Mythago Wood",
  "Narnia",
  "never-never-land",
  "Oblivion",
  "Oompa-loompa Land",
  "outer space",
  "Oz",
  "Park Hill Flats",
  "Siberia",
  "Sid's Café",
  "Skegness",
  "the Australian Outback",
  "the centre of an Aztec pyramid",
  "the Earth's core",
  "the edgelands",
  "the Enchanted Forest",
  "the eye of a needle",
  "the Ghobi Desert",
  "the Grand Canyon",
  "the heart of darkness",
  "the Himalayas",
  "the kingdom of Bryneich",
  "the Midwest",
  "the North of England",
  "the Outer Hebrides",
  "the Pastel City",
  "the Peak District",
  "the place you least expect",
  "the roots of an ancient #tree# tree",
  "the salt marshes",
  "the Shire",
  "the Solar System",
  "the space-time continuum",
  "the TARDIS",
  "the Thursbitch valley",
  "the tundra",
  "the Twilight Zone",
  "the Western Spiral Arm of the galaxy",
  "Timbuktu",
  "Viriconium",
  "Westeros",
  "Xanadu",
  "your backyard",
  "your sock drawer"
];

const atPlace = [
  "Ox Stones",
  "Stonehenge",
  "the edge of time",
  "The Restaurant at The End of The Universe"
];

const onPlace = [
  "a mountain the size of a pinhead",
  "a static caravan site in Ingoldmells",
  "Alpha Centuri",
  "Ben Nevis",
  "Betelgeuse",
  "Burbage Moor",
  "Earthsea",
  "Everest",
  "Golgafrincham",
  "Kinder Scout",
  "Mars",
  "Naboo",
  "Netpune",
  "Oceanworld",
  "Stanage Edge",
  "Stavromula Beta",
  "Tatooine",
  "the astral plane",
  "the banks of Lake Windermere",
  "the Forest of Boland Light Railway",
  "the Frogstar",
  "the head of a pin",
  "the Orient Express",
  "the other side of the veil",
  "the outskirts of infinity",
  "the World of Two Moons",
  "Traal",
  "Uranus",
  "Ursa Minor Beta",
  "Vogsphere",
  "Win Hill"
];

const unqualifiedPlace = ["deep beneath the ground", "six feet underground"];

const qualifiedPlace = unqualifiedPlace.concat(
  atPlace.map(place => `at ${place}`),
  inPlace.map(place => `in ${place}`),
  onPlace.map(place => `on ${place}`)
);
const placeName = atPlace.concat(inPlace, onPlace);
module.exports = {
  dwelling,
  qualifiedPlace,
  unqualifiedPlace,
  worshipPlace,
  placeName,
  inPlace,
  atPlace,
  onPlace,
  settings,
  venues
};
