module.exports = [
  "accountancy",
  "aesthetics",
  "agriculture",
  "anatomy",
  "anthropology",
  "archery",
  "architecture",
  "arseholeism",
  "art",
  "aviation",
  "ballet",
  "bareback riding",
  "biography",
  "biology",
  "business accounting",
  "chemotherapy",
  "choreography",
  "cryptography",
  "divination",
  "epistemology",
  "hauntology",
  "hotel management",
  "jurisprudence",
  "literature",
  "logic",
  "lovemaking",
  "massage therapy",
  "media studies",
  "mediation",
  "phenomenology",
  "philosophy",
  "phrenology",
  "prognostication",
  "self-improvement",
  "semiotics",
  "skillz",
  "sociology",
  "sports science",
  "theology",
  "therapy",
  "witchcraft",
  "#nationality# studies",
  "advanced #academicField#",
  "applied #academicField#"
];
