module.exports = [
  "accountancy",
  "aesthetics",
  "agriculture",
  "all the 'ologies",
  "anatomy",
  "anthropology",
  "archery",
  "architecture",
  "arseholeism",
  "art",
  "aviation",
  "ballet",
  "bareback riding",
  "biography",
  "biology",
  "bogeyology",
  "business accounting",
  "buttography",
  "chemotherapy",
  "choreography",
  "crapology",
  "cryptography",
  "divination",
  "epistemology",
  "flatulentalism",
  "gelatinology",
  "hauntology",
  "hermeneutics",
  "hierology",
  "hotel management",
  "jurisprudence",
  "knitting",
  "literature",
  "logic",
  "lovemaking",
  "massage therapy",
  "media studies",
  "mediation",
  "mediocrity",
  "ologyology",
  "philately",
  "phenomenology",
  "philosophy",
  "phrenology",
  "prognostication",
  "self-improvement",
  "semiotics",
  "skillz",
  "sociology",
  "sports science",
  "tapestry-making",
  "theology",
  "therapy",
  "twattism",
  "witchcraft",
  "#nationality# studies",
  "advanced #academicField#",
  "applied #academicField#"
];
