const birdType = [
  "bittern",
  "godwit",
  "blackbird",
  "grouse",
  "guillemot",
  "redstart",
  "grebe",
  "moorhen",
  "heron",
  "diver",
  "brambling",
  "buzzard",
  "bullfinch",
  "egret",
  "warbler",
  "chiffchaff",
  "chough",
  "redpoll",
  "hobby",
  "jackdaw",
  "jay",
  "dove",
  "pigeon",
  "sandpiper",
  "corncrake",
  "coot",
  "woodcock",
  "lark",
  "wagtail",
  "yellowhammer",
  "twite",
  "waxwing",
  "wigeon",
  "parrot",
  "parakeet",
  "mynah",
  "tree",
  "crossbill",
  "partridge",
  "goldeneye",
  "oriole",
  "quail",
  "turkey",
  "osprey",
  "chicken",
  "chick",
  "skua",
  "albatross",
  "cormorant",
  "shag",
  "petrel",
  "duck",
  "goose",
  "swan",
  "gull",
  "shearwater",
  "booby",
  "gannet",
  "woodpecker",
  "auk",
  "dodo",
  "fulmar",
  "sheathbill",
  "tern",
  "bufflehead",
  "smew",
  "magpie",
  "crow",
  "rook",
  "raven",
  "starling",
  "thrush",
  "wren",
  "sparrow",
  "tit",
  "finch",
  "peewit",
  "lapwing",
  "oystercatcher",
  "kestrel",
  "hawk",
  "vulture",
  "eagle",
  "robin",
  "chaffinch",
  "ptarmigan",
  "warbler",
  "avocet",
  "owl",
  "curlew",
  "swift",
  "swallow",
  "martin",
  "shrike",
  "ouzel",
  "kite",
  "merlin",
  "harrier",
  "nightingale",
  "peregrine",
  "nuthatch",
  "kingfisher",
  "queenfisher",
  "fulmar",
  "dunnock",
  "firecrest",
  "phoenix",
  "feathered dinosaur"
];

const birdBodyPlace = [
  "mantled",
  "winged",
  "billed",
  "footed",
  "breasted",
  "tailed",
  "headed",
  "backed",
  "capped",
  "crowned",
  "knee"
];

const birdAdjective = [
  "whooping",
  "Eurasian",
  "solitary",
  "little",
  "elegant",
  "Caspian",
  "barn",
  "boreal",
  "nocturnal",
  "ringed",
  "belted",
  "greenish",
  "vermilion",
  "social",
  "cave",
  "sedge",
  "mountain",
  "steppe",
  "snow",

  "mottled",
  "Cook's",
  "Brown's",
  "Drumpf's",
  "Murphy's",
  "Audubon's",
  "neotropic",
  "pelagic",
  "tricolored",
  "harlequin",
  "pied",
  "cattle",
  "fish",

  "wandering",
  "sooty",
  "#adjective#-mantled",
  "Arctic",
  "Antarctic",
  "imperial",
  "emperor",
  "empress",
  "diving",
  "giant",
  "pygmy",
  "southern",
  "northern",
  "eastern",
  "western",
  "common",
  "barnacle",
  "mute",
  "muscovy",
  "Egyptian",
  "American",
  "Asian",
  "Antipodean",
  "equatorial",
  "wood",
  "greater-spotted",
  "spectacled",
  "lesser-spotted",
  "cape",
  "snow",
  "scaly",
  "Himalayan",
  "Saharan",
  "wild",
  "#tree#",
  "Atlantic",
  "Pacific",
  "space",
  "interstellar",
  "galactic",
  "least",
  "horned",
  "barn",
  "lesser",
  "greater",
  "aquatic",
  "house",
  "rock"
];

const bird = [
  "#birdAdjective# #birdType#",
  "#birdAdjective# #adjective#-#birdBodyPlace# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective# #birdType#",
  "#adjective#-#birdBodyPlace# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective# #birdType#",
  "#adjective#-#birdBodyPlace# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective# #birdType#",
  "#adjective#-#birdBodyPlace# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective# #birdType#",
  "#adjective#-#birdBodyPlace# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective# #birdType#",
  "#adjective#-#birdBodyPlace# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective# #birdType#",
  "#adjective#-#birdBodyPlace# #birdType#",
  "#adjective#-#birdBodyPlace# #birdAdjective##birdType#",
  "#adjective# #birdType#",
  "#birdType#"
];

module.exports = {
  bird,
  birdType,
  birdAdjective,
  birdBodyPlace
};
