const corpora = require("corpora-project");

const borrowedFromABot = [
  "1/8-inch rubber sheeting",
  "a 200-foot drop",
  "a battery-powered singing fish",
  "a box of sugar cubes",
  "a bubble machine",
  "a cardboard box",
  "a clawfoot tub",
  "a clean, intact eggshell",
  "a couple of Pringles cans",
  "a couple of big springs",
  "a couple of plastic buckets",
  "a divining rod",
  "a dozen beeswax candles",
  "a fire truck",
  "a fog machine",
  "a garbage can",
  "a garbage truck",
  "a ghost detector",
  "a handful of pennies",
  "a hollow log",
  "a knotted strand of pearls",
  "a lacquered gourd",
  "a large metal whisk",
  "a metal rake",
  "a modified Speak'n'Spell",
  "a patch of desert",
  "a pinball cabinet",
  "a pound of live crickets",
  "an electric pencil sharpeners",
  "a refrigerator door",
  "a rubber syringe",
  "a satellite dish",
  "a series of aromas",
  "a simulated cat",
  "a smoke detector",
  "a steel hoop",
  "a sturdy desk fan",
  "a tame squirrel",
  "a tin box",
  "a washing machine",
  "a watermelon",
  "a wooden box",
  "a wooden staircase",
  "air currents",
  "aluminum conduit",
  "an aluminum pie plate",
  "an array of bug zappers",
  "an array of heavy brass door-knockers",
  "an automatic towel dispenser",
  "an imperfectly trained chicken",
  "ball bearings",
  "bamboo parasols",
  "bamboo skewers",
  "bees",
  "bicycle spokes",
  "big steel mixing bowls",
  "biological data",
  "birch bark",
  "birthday candles",
  "black lead",
  "black thread",
  "bodily fluids",
  "boiling water",
  "bones",
  "bronze bars",
  "bubble wrap",
  "bullet casings",
  "carved bone dice",
  "cellophane",
  "chalk",
  "chandelier prisms",
  "chess algorithms",
  "cigarettes",
  "clamshells",
  "clay flowerpots",
  "cleavers",
  "clock mechanisms",
  "cocktail stirrers",
  "coffee grinders",
  "coffee grounds",
  "copper pipes",
  "cornmeal",
  "crushed charcoal",
  "dandelion seeds",
  "degraded magnetic tape",
  "dirt",
  "disc drives",
  "dry grass",
  "dry leaves",
  "egg slicers",
  "elastic cords",
  "electric drills",
  "electric toothbrushes",
  "electromagnets",
  "falling snow",
  "false teeth",
  "feathers",
  "fiddler crabs",
  "film reels",
  "fire hoses",
  "fishing line",
  "flex sensors",
  "flour sifters",
  "freshwater algae",
  "fur",
  "gelatin",
  "gizzards and offal",
  "glass cylinders",
  "glass eyes",
  "glass plaques",
  "glass tubes",
  "glue",
  "googly eyes",
  "gumball machine mechanisms",
  "hairbrushes",
  "hand-cranked eggbeaters",
  "hazelnuts",
  "heart rate monitors",
  "heavy old doors",
  "high-carbon steel wires",
  "honey",
  "ice",
  "iron keys",
  "javascript",
  "knitting instructions",
  "lasers",
  "lipstick tubes",
  "live plants",
  "lots of little springs",
  "love letters",
  "machine vision",
  "magnetic putty",
  "magnetic tape",
  "marbles",
  "mayonnaise",
  "metronomes",
  "mosquitoes",
  "moss",
  "motion sensors",
  "mussel shells",
  "mylar balloons",
  "nail clippers",
  "nails in various sizes",
  "oceanographic data",
  "official redactions",
  "old shaving brushes",
  "packing tape",
  "pager motors",
  "paper cups",
  "paper shredders",
  "paper straws",
  "pearls",
  "pennies, dimes, nickels,",
  "pepper grinders",
  "piano wire",
  "pine needles",
  "ping-pong balls",
  "planks of dense wood",
  "plastic bananas",
  "plastic wrap",
  "playing cards",
  "pneumatic bladders",
  "popcorn",
  "poppy seedheads",
  "potato chip bags",
  "pressurized air",
  "puppy dog's tails",
  "push lawnmowers",
  "rain",
  "reclaimed bricks",
  "rock salt",
  "rose petals",
  "roses",
  "rotary telephone dials",
  "rubber balls",
  "rubber bands",
  "rune stones",
  "rusty shopping-cart wheels",
  "sand",
  "sandpaper",
  "saw blades",
  "sawdust pellets",
  "seawater",
  "seismic sensors",
  "seltzer water",
  "several dozen tiny brass bells",
  "several electric pencil sharpeners",
  "sewer pipes",
  "sewing machines",
  "shovels",
  "silver knives",
  "slate tiles",
  "small bonfires",
  "small ceramic bowls",
  "small polished stones",
  "smoke",
  "snail trails",
  "sneezing",
  "soda cans",
  "solenoids",
  "some carefully managed rattlesnakes",
  "some gumption",
  "sourdough starter",
  "spiders",
  "spinning wheels",
  "spray paint cans",
  "squeaky dog toys",
  "steam",
  "steel chains",
  "steel needles",
  "stepper motors",
  "stretchy exercise bands",
  "sugar and spice",
  "sugar tongs",
  "sunspot data",
  "surgical tubing",
  "sweeper bristles",
  "tarot cards",
  "temperature sensors",
  "the Doppler effect",
  "the Dow Jones index",
  "the Oxford English Dictionary",
  "the tops of baby food jars",
  "thick bamboo poles",
  "thimbles",
  "thin paper",
  "thin-walled mixing bowls",
  "thistles",
  "tides",
  "tin cans",
  "tiny bonfires",
  "tiny explosions",
  "tongue depressors",
  "toothpaste",
  "toy cars",
  "toy tops",
  "two hundred canaries",
  "typewriter parts",
  "ultrasonic range finders",
  "vacuum cleaner parts",
  "velcro",
  "vinegar, baking soda,",
  "walk signals",
  "walnut shells",
  "warm honey",
  "water",
  "wax beads",
  "waxed paper parasols",
  "weather data",
  "willow branches",
  "wind",
  "wind-up toys",
  "wood ash",
  "wooden alphabet blocks",
  "wooden shoes",
  "yardsticks",
  "yarrow stalks"
];

module.exports = corpora
  .getFile("materials", "building-materials")
  ["building materials"].concat(
    [
      "#animal.s#' tears",
      "#animal.s#' teeth",
      "#animal# blood",
      "#buildingMaterial# and #buildingMaterial#",
      "#foodStuff#",
      "#liquid#",
      "#bird# feathers",
      "#bird.s#' beaks",
      "armloads of stars",
      "bile and regret",
      "blood and bone",
      "blood and sand",
      "burnished gold",
      "cartilage",
      "chitin",
      "clay and sheep dung",
      "cornstarch",
      "cytoplasm",
      "darkness",
      "death",
      "diet Coke and Mentos",
      "ectoplasm",
      "electricity",
      "Euros",
      "faeces",
      "glass and steel",
      "glitter",
      "grammar",
      "greenery",
      "happiness",
      "hate",
      "human bones",
      "human cares",
      "human hair",
      "human happiness",
      "human woe",
      "insects",
      "iron forged in the fires of #placeName#",
      "jellyfish",
      "knicker-elastic",
      "laminate flooring",
      "lichen",
      "life",
      "lycra",
      "manta ray leather",
      "memories",
      "mitochondria",
      "nylon",
      "oxygen",
      "phosphorus",
      "pig iron",
      "planished copper",
      "plasma",
      "polycarbon",
      "potassium",
      "sand",
      "sheep skulls",
      "sorrow",
      "sterling silver",
      "straw",
      "taxes",
      "tears",
      "tears of the departed",
      "thousand-year-old #tree# timber",
      "tweets",
      "weapons-grade plutonium"
    ].concat(borrowedFromABot)
  );
