const corpora = require("corpora-project");
module.exports = corpora
  .getFile("materials", "building-materials")
  ["building materials"].concat([
    "#animal.s#' tears",
    "#animal.s#' teeth",
    "#animal# blood",
    "#buildingMaterial# and #buildingMaterial#",
    "#foodStuff#",
    "#liquid#",
    "armloads of stars",
    "bile and regret",
    "blood and bone",
    "blood and sand",
    "burnished gold",
    "cartilage",
    "chitin",
    "clay and sheep dung",
    "cornstarch",
    "cytoplasm",
    "darkness",
    "death",
    "diet Coke and Mentos",
    "ectoplasm",
    "electricity",
    "Euros",
    "faeces",
    "glass and steel",
    "glitter",
    "grammar",
    "greenery",
    "happiness",
    "hate",
    "human bones",
    "human cares",
    "human hair",
    "human happiness",
    "human woe",
    "insects",
    "iron forged in the fires of #placeName#",
    "jellyfish",
    "knicker-elastic",
    "laminate flooring",
    "lichen",
    "life",
    "lycra",
    "manta ray leather",
    "memories",
    "mitochondria",
    "nylon",
    "oxygen",
    "phosphorus",
    "pig iron",
    "planished copper",
    "plasma",
    "polycarbon",
    "potassium",
    "sand",
    "sheep skulls",
    "sorrow",
    "sterling silver",
    "straw",
    "taxes",
    "tears",
    "tears of the departed",
    "thousand-year-old #tree# timber",
    "tweets",
    "weapons-grade plutonium"
  ]);
