module.exports = [
  "zip file",
  "data visualisation",
  "GIF",
  "enterprise software",
  "lambda function",
  "syntax",

  "cursor",
  "#adjective# error",
  "stack overflow",
  "python script",
  "database",
  "virus",
  "Trojan horse",
  "pixel",
  "cure for cancer",
  "game",
  "algorithm",
  "folder",
  "alert",
  "pop-up",
  "browser window",
  "keyboard shortcut",
  "neat hack",
  "terminal window",
  "chatbot",
  "help file"
];
