module.exports = [
  "acne",
  "anomia",
  "asthma",
  "cancer",
  "cholera",
  "death",
  "depression",
  "dsyexlia",
  "epilepsy",
  "fear of #nounToPluralise.s#",
  "forgetfulness",
  "gout",
  "palsy",
  "phobia of #nounToPluralise.s#",
  "pimples",
  "pleurisy",
  "pneumonia",
  "suffering",
  "#name#'s disease"
];
