module.exports = [
  "Abraham Lincoln",
  "Adolf Hitler",
  "Albert Einstein",
  "Anton LaVey",
  "Arnold Schwarzenegger",
  "Bill Drummond",
  "Boris Johnson",
  "Bruce Lee",
  "Charlie Chaplin",
  "David Beckham",
  "David Bowie",
  "Doctor Who",
  "Donald Drumpf",
  "Donald Trump",
  "Elvis Presley",
  "Jacob Rees-Mogg",
  "Jeremy Corbyn",
  "Jesus",
  "Jimmy Cauty",
  "Keith Flint",
  "Ken Campbell",
  "Madonna",
  "Mao Tse Tung",
  "Margaret Thatcher",
  "Michael Gove",
  "Michael Jackson",
  "Mother Theresa",
  "Muhammad Ali",
  "Richard Nixon",
  "Robert Anton Wilson",
  "Ronald Reagan",
  "Rupert Murdoch",
  "Shirley Temple",
  "Sting",
  "Theresa May (I know, who?)"
];
