module.exports = [
  "Abraham Lincoln",
  "Adelle",
  "Adolf Hitler",
  "Alan Moore",
  "Albert Einstein",
  "Alfred Hitchcock",
  "Anton LaVey",
  "Arnold Schwarzenegger",
  "Audrey Hepburn",
  "Barack Obama",
  "Bill Drummond",
  "Boris Johnson",
  "Bruce Lee",
  "Caravaggio",
  "Charlie Chaplin",
  "Cristiano Ronaldo",
  "David Beckham",
  "David Bowie",
  "Doctor Who",
  "Donald Drumpf",
  "Donald Trump",
  "Dwayne Johnson",
  "Edgar Allan Poe",
  "Edvard Munch",
  "Elvis Presley",
  "Eminem",
  "Freddie Mercury",
  "George Harrison",
  "Germaine Greer",
  "Grant Morrison",
  "Hillary Clinton",
  "HP Lovecraft",
  "HP Sexart",
  "Jacob Rees-Mogg",
  "Jennifer Lopez",
  "Jeremy Corbyn",
  "Jesus",
  "Jimmy Cauty",
  "John Cage",
  "John F Kennedy",
  "John Lennon",
  "Johnny Depp",
  "Julius Caesar",
  "Kanye",
  "Keith Flint",
  "Ken Campbell",
  "Kim Kardashian",
  "Kurt Vonnegut",
  "Madonna",
  "Mao Tse Tung",
  "Margaret Thatcher",
  "Marilyn Monroe",
  "Michael Gove",
  "Michael Jackson",
  "Mother Theresa",
  "Muhammad Ali",
  "Neil Gaiman",
  "Oprah Winfrey",
  "Paul McCartney",
  "Prince Andrew",
  "Prince Harry",
  "Prince William",
  "Princess Diana",
  "Queen Elizabeth II",
  "Richard Nixon",
  "Ringo Starr",
  "Robert Anton Wilson",
  "Ronald Reagan",
  "Rupert Murdoch",
  "Salvador Dali",
  "Shirley Temple",
  "Sting",
  "The Masked Singer",
  "Theresa May (I know, who?)"
];
