module.exports = [
  "ammonia",
  "honey",
  "gin",
  "eau de vie",
  "asses milk",
  "#animal.s# milk",
  "barley wine",
  "stagnant water",
  "vinegar",
  "grape nut oil",
  "engine oil",
  "#animal# blood",
  "human blood",
  "whisky",
  "aqua vita",
  "absinthe",
  "acid",
  "#animal# tears",
  "babys' tears",
  "bile",
  "#animal# urine",
  "ectoplasm",
  "molasses",
  "astral goo",
  "schnapps",
  "sperm",
  "tequila",
  "Yorkshire tea",
  "#wineDescriptions# wine",
  "chamomile tea"
];
