module.exports = [
  "#animal.s# milk",
  "#animal# blood",
  "#animal# tears",
  "#animal# urine",
  "#wineDescriptions# wine",
  "absinthe",
  "acid",
  "ammonia",
  "aqua vita",
  "asses milk",
  "astral goo",
  "babys' tears",
  "barley wine",
  "bile",
  "chamomile tea",
  "eau de vie",
  "ectoplasm",
  "engine oil",
  "gin",
  "grape nut oil",
  "honey",
  "human blood",
  "molasses",
  "schnapps",
  "sperm",
  "stagnant water",
  "tequila",
  "vinegar",
  "whisky",
  "Yorkshire tea"
];
