module.exports = [
  "#animal.s# milk",
  "#animal# blood",
  "#animal# tears",
  "#animal# urine",
  "#animal# venom",
  "#wineDescriptions# wine",
  "absinthe",
  "acid",
  "ammonia",
  "angels' tears",
  "aqua vita",
  "asses milk",
  "astral goo",
  "babys' tears",
  "barley wine",
  "bile",
  "chamomile tea",
  "dew drops",
  "eau de vie",
  "ectoplasm",
  "engine oil",
  "gin",
  "gob",
  "grape nut oil",
  "gravy",
  "Henderson's Relish",
  "holy water",
  "honey",
  "human blood",
  "liquid earwax",
  "mastiha",
  "molasses",
  "nectar",
  "pus",
  "river water",
  "schnapps",
  "šljȉvovica",
  "snot",
  "sperm",
  "spunk",
  "sputum",
  "stagnant water",
  "swamp water",
  "syrup",
  "tequila",
  "#tree# sap",
  "vinegar",
  "whisky",
  "Yorkshire tea"
];
