module.exports = [
  "friend request",
  "malapropism",
  "pinball machine",
  "arcade machine",
  "iPhone",
  "banjo",
  "barrier",
  "electronica album",
  "lanyard",
  "wallpaper brush",
  "paint roller",
  "wheeled suitcase",
  "drainpipe",
  "LED lightbulb",
  "door frame",
  "Harry Potter fanfic",
  "chocolate egg",
  "basin",
  "battery",
  "belisha beacon",
  "cassette",
  "coaster",
  "computer monitor",
  "dank meme",
  "detox",
  "dollar",
  "dolls' house",
  "doorstep",
  "doorway",
  "drinking fountain",
  "e-cigarette",
  "elbow patch",
  "embroidery",
  "thermos flask",
  "fruitbowl",
  "fry-up",
  "fuck-up",
  "gubbins",
  "hallway",
  "hammock",
  "headset",
  "hearth",
  "laser",
  "lampshade",
  "mainframe",
  "microwave",
  "monolith",
  "novella",
  "porno",
  "projector",
  "prospectus",
  "recipe",
  "refrigerator",
  "roadblock",
  "rock",
  "rood screen",
  "safety barrier",
  "saucer",
  "semiconductor",
  "shitstorm",
  "snapshot",
  "souvenir",
  "staircase",
  "stairway",
  "stylus",
  "tablespoon",
  "telephone",
  "thriller",
  "treadmill",
  "tricycle",
  "ventilation shaft",
  "wardrobe",
  "wedding list",
  "widget",
  "incense stick",
  "prayer mat",
  "tarot deck",
  "temple bell",
  "religious symbol",
  "family heirloom"
];
