module.exports = [
  "arcade machine",
  "banjo",
  "barrier",
  "basin",
  "bathyscope",
  "battery",
  "belisha beacon",
  "cassette",
  "chocolate egg",
  "coaster",
  "computer monitor",
  "dank meme",
  "detox",
  "dollar",
  "dolls' house",
  "door frame",
  "doorstep",
  "doorway",
  "drainpipe",
  "drinking fountain",
  "e-cigarette",
  "elbow patch",
  "electronica album",
  "embroidery",
  "family heirloom",
  "fatberg",
  "friend request",
  "fruitbowl",
  "fry-up",
  "fuck-up",
  "gubbins",
  "hallway",
  "hammock",
  "Harry Potter fanfic",
  "headset",
  "hearth",
  "Higgs boson",
  "incense stick",
  "iPhone",
  "lampshade",
  "lanyard",
  "laser",
  "LED lightbulb",
  "mainframe",
  "malapropism",
  "microwave",
  "monolith",
  "novella",
  "paint roller",
  "pinball machine",
  "porno",
  "prayer mat",
  "projector",
  "prospectus",
  "recipe",
  "refrigerator",
  "religious symbol",
  "roadblock",
  "rock",
  "rood screen",
  "safety barrier",
  "saucer",
  "semiconductor",
  "shitstorm",
  "snapshot",
  "souvenir",
  "spy camera",
  "staircase",
  "stairway",
  "stylus",
  "tablespoon",
  "tarot deck",
  "telephone",
  "temple bell",
  "thermos flask",
  "thriller",
  "treadmill",
  "tricycle",
  "ventilation shaft",
  "wallpaper brush",
  "wardrobe",
  "wedding list",
  "wheeled suitcase",
  "widget"
];
