module.exports = {
  deliverMessage: [
    "delivers, through the medium of interpretive dance, the message",
    "hands you #miscObject.a#, on which is written",
    "hands you a note which reads",
    "reads from a stone tablet the words:",
    "semaphores to you the message",
    "sings you a ballad, which begins",
    "spells out in sign-language the words",
    "whispers in your ear",
    "whispers that you should"
  ],
  busyActivity: [
    "is showering in #adjective# #liquid#",
    "has #adjective.a# headache",
    "shuffles away #adverb#",
    "shoots you a look that could kill #animal.s# from a hundred paces"
  ],
  busyInstruction: [
    ". Come back later",
    ", and can't talk to you right now",
    ". Perhaps this is not the best time to call?",
    ". They might respond if you call a little louder?",
    ". Maybe you ought to respect #deityName#'s privacy a little more?",
    ". #deityThey# just needs #takesTime#",
    ". Come back after #takesTime#",
    ". Come back at #specificTime#"
  ],
  deityRequest: [
    "borrow",
    "impregnate",
    "despoil",
    "sit on",
    "fiddle with",
    "make babies with",
    "ennoble",
    "create life from",
    "begin a cult that worships",
    "judge",
    "dance with",
    "exchange places with",
    "give your soul to",
    "googlewhack",
    "imagine",
    "consider",
    "make a mental sketch of",
    "imagine you were",
    "become a trainer of",
    "consume only",
    "spread the word about",
    "talk with",
    "commune with",
    "refrigerate",
    "customise",
    "consider",
    "indoctrinate",
    "destroy all",
    "capture the souls of",
    "start a new society based on",
    "defend your soul from",
    "open your heart to",
    "place yourself on an equal footing with",
    "deviate from"
  ]
};
