module.exports = [
  '#deityName# appears\nIn front of the head office\nOf #company#\nAnd orders those inside\nTo "#followerAction#".',
  '#deityName# left a sign saying\n"OUT #twoPersonAction.toUpperCase# #otherDeity.toUpperCase#".',
  "#deityName# #asks# you\nTo meditate on the topic\nOf #nounNotToPluralise#.",
  "#deityName# #busyActivity#.",
  "#deityName# appears\nIn the form of #deityTheir# spirit animal,\n#adjective.a.capitalize# #spiritAnimal#.\nThe #spiritAnimal#\nLooks at you #adverb#\nAnd #animalAction.s#.",
  "#deityName# appears\nThrough the #adjective# mist,\nAnd thanks you for your patience.",
  "#deityName# builds\n#adjective.a.capitalize# #worshipPlace#\nTo #deityDomain#\n#reason.capitalize#.",
  "#deityName# builds\n#dwelling.a.capitalize#\nIn #deityPlace#\n#reason.capitalize#.",
  "#deityName# calls down a shower\nOf #liquid#\n#reason.capitalize#.",
  "#deityName# challenges you\nTo a game of #game#.\n\nDo you accept?",
  "#deityName# climbs\n#tree.a.capitalize# tree\nIn order to better survey #deityTheir# domain.\n\nSomething in the distance\nGives #deityThem#\nA profound feeling\nOf #feeling#.",
  "#deityName# conjures #nounToPluralise.a#\nFrom thin air,\nAnd offers it to you\n#reason.capitalize#.",
  "#deityName# cries\nTears of #liquid#,\nWhich form into a pool;\n#animal.s.capitalize#\nGather around the pool\nTo drink.",
  "#deityName# demands\nThat you make a sacrifice\nOf burnt #foodStuff#,\nOffered up\nIn #nounToPluralise.a#\nMade from #buildingMaterial#.",
  "#deityName#\nGestures at your #nounToPluralise#\n#adverb.capitalize#\n#reason.capitalize#.",
  "#deityName# has hidden\n#computerObject.a.capitalize# on your computer.\n\nCan you find it?",
  "#deityName#\nIs #making#\nFor the forthcoming\n#festival.capitalize#.",
  "#deityName#\nIs #making#,\nAnd thinks that you\nShould do likewise.",
  "#deityName#\nIs #twoPersonAction# #characterName#\nIn #deityPlace#\n#reason.capitalize#.",
  "#deityName#\nIs about to ask you\nTo sacrifice #animal.a#,\nBut thinks better of it\nAnd asks you to sacrifice\n#nounToPluralise.a.capitalize#\nInstead.",
  "#deityName#\nIs admiring\n#characterName.capitalize#\nin a mirror-smooth pool\nOf #nounNotToPluralise#.",
  "#deityName#\nIs cooking\n#foodItem.s.capitalize# made of #foodStuff#\nFor tea.\n\nWould you like some?",
  "#deityName#\nIs decorating\n#deityTheir# #dwelling#\nIn #deityPlace#,\nWith a wallpaper of #nounToPluralise.s#\nUpon #nounNotToPluralise#.",
  "#deityName#\nIs feeling\nA bit #adjective# today.\n\nPerhaps come back tomorrow?",
  "#deityName#\nIs often worshippedDuring #festival#\n#reason.capitalize#.",
  "#deityName# just made\nAn extremely #jokeAdjective# joke\nAbout #adjective# #nounToPluralise.s#.",
  "#deityName# offers you\nA choice between\n#nounToPluralise.a.capitalize#,\n#nounToPluralise.a.capitalize#\nAnd #nounToPluralise.a#.\n\nWhich do you choose?",
  "#deityName# pimps your ride.\n\nHow d'you fancy going home\nIn #adjective.a# #vehicle#?",
  "#deityName# plants #tree.a# tree\nWith #adjective.a# heart.\n\nUnder the tree's roots\n#adjective.a.capitalize# #nounToPluralise# is buried\nFor its powers\nOf #quality#.",
  "#deityName# plays\nWith #characterName#\nIn #band.a#\nAt #deityPlace#.\n\n#bandStory#.",
  "#deityName# pushes\nThe first bud of #flower.a#\nThrough the earth's mantle\nOf #buildingMaterial#.",
  "#deityName# rattles\nA tin under your nose\nAnd asks for a donation\nTo save the #animal.s#.",
  "#deityName# rewards you\nFor your loyalty\nWith #nounToPluralise.a#.",
  "#deityName# shits out\nA huge mound of #buildingMaterial#.\n\nImmediately,\n#flower.s.capitalize# start to grow\nOut of the mound\nTowards you.",
  "#deityName#\nSpends #takesTime#\n#meditating# #object#.",
  "#deityName#\nsticks #nounToPluralise.a#\n#preposition.capitalize# #nounToPluralise.a#\nAnd uses it\n#reason.capitalize#.",
  "#deityName# will reward you\nFor your loyalty,\nAlthough you will have to wait.",
  "#wind.a# stirs\nThe #tree# trees.\n\n#deityFull# sighs\n#adverb.capitalize#.",
  "In #dwelling.a#\nIn #deityPlace#,\nYou see #deityName#\nAnd #characterName#\n#making.capitalize#.",
  "It seems that #deityName# #busyActivity##busyInstruction#.",
  "There is no reply.\nPerhaps #deityName#\nIs #twoPersonAction#\nAnother #deityType#?"
];
