module.exports = [
  '#deityName# appears in front of the head office of #company# and orders those inside to "#followerAction#".',
  '#deityName# left a sign saying "OUT #twoPersonAction.toUpperCase# #otherDeity.toUpperCase#".',
  "#deityName# #asks# you to meditate on the topic of #nounNotToPluralise#.",
  "#deityName# #busyActivity#.",
  "#deityName# appears in the form of #deityTheir# spirit animal, #adjective.a# #spiritAnimal#. The #spiritAnimal# looks at you #adverb# and #animalAction.s#.",
  "#deityName# appears through the #adjective# mist, and thanks you for your patience.",
  "#deityName# builds #adjective.a# #worshipPlace# to #deityDomain# #reason#.",
  "#deityName# builds #dwelling.a# in #deityPlace# #reason#.",
  "#deityName# calls down a shower of #liquid# #reason#.",
  "#deityName# challenges you to a game of #game#. Do you accept?",
  "#deityName# climbs #tree.a# tree in order to better survey #deityTheir# domain. Something in the distance gives #deityThem# a profound feeling of #feeling#.",
  "#deityName# conjures #nounToPluralise.a# from thin air, and offers it to you #reason#.",
  "#deityName# cries tears of #liquid#, which form into a pool; #animal.s# gather around the pool to drink.",
  "#deityName# demands that you make a sacrifice of burnt #foodStuff#, offered up in #nounToPluralise.a# made of #buildingMaterial#.",
  "#deityName# gestures at your #nounToPluralise# #adverb# #reason#.",
  "#deityName# has hidden #computerObject.a# on your computer. Can you find it?",
  "#deityName# is #making# for the forthcoming #festival#.",
  "#deityName# is #making#, and thinks you should do likewise.",
  "#deityName# is #twoPersonAction# #characterName# in #deityPlace# #reason#.",
  "#deityName# is about to ask you to sacrifice #animal.a#, but thinks better of it and asks you to sacrifice #nounToPluralise.a# instead.",
  "#deityName# is admiring #characterName# in a mirror-smooth pool of #nounNotToPluralise#.",
  "#deityName# is cooking #foodItem.s# made of #foodStuff# for tea. Would you like some?",
  "#deityName# is decorating #deityTheir# #dwelling# in #deityPlace#, with a wallpaper of #nounToPluralise.s# upon #nounNotToPluralise#.",
  "#deityName# is feeling a bit #adjective# today. Perhaps come back tomorrow?",
  "#deityName# is often worshipped during #festival# #reason#.",
  "#deityName# just made an extremely #jokeAdjective# joke about #adjective# #nounToPluralise.s#.",
  "#deityName# offers you a choice between #nounToPluralise.a#, #nounToPluralise.a# and #nounToPluralise.a#. Which do you choose?",
  "#deityName# pimps your ride. How d'you fancy going home in #adjective.a# #vehicle#?",
  "#deityName# plants #tree.a# tree with #adjective.a# heart. Under the tree's roots #adjective.a# #nounToPluralise# is buried for its powers of #quality#.",
  "#deityName# plays with #characterName# in #band.a# at #deityPlace#. #bandStory#.",
  "#deityName# pushes the first bud of #flower.a# through the earth's mantle of #buildingMaterial#.",
  "#deityName# rattles a tin under your nose and asks for a donation to save the #animal.s#.",
  "#deityName# rewards you for your loyalty with #nounToPluralise.a#.",
  "#deityName# shits out a huge mound of #buildingMaterial#. Immediately, #flower.s# start to grow out of the mound towards you.",
  "#deityName# spends #takesTime# #meditating# #object#.",
  "#deityName# sticks #nounToPluralise.a# #preposition# #nounToPluralise.a# and uses it #reason#.",
  "#deityName# will reward you for your loyalty, although you will have to wait.",
  "#wind.a# stirs the #tree# trees. #deityFull# sighs #adverb#.",
  "in #dwelling.a# in #deityPlace#, you see #deityName# and #characterName# #making#.",
  "it seems that #deityName# #busyActivity##busyInstruction#.",
  "there is no reply. Perhaps #deityName# is #twoPersonAction# another #deityType#?"
];
