module.exports = {
  followerAction: [
    "#instruction#",
    "#verb# #object#",
    "#pilgrimage#",
    "#meditation#",
    "#quest#"
  ],
  pilgrimage: [
    "#travel#\nWith #deityName#'s #role#\nTo #pilgrimageSite#",
    "#travel#\nTo #pilgrimageSite#\nAnd #quest#",
    "#travel#\nTo #pilgrimageSite#",
    "gather your #spiritAnimal.s#\nAnd form\n#band.a.capitalize#"
  ],
  quest: [
    "find #adjective.a# #nounToPluralise#",
    "capture #bird.a#.\nKiss it,\ncuddle it,\nand set it free",
    "devote your life\nTo studying the #academicField#\nOf #deityDomain#",
    "leave your #bodyPart# behind",
    "sacrifice\n#animal.a.capitalize#",
    "observe the world\n#adverb.capitalize#",
    "spread the good news\nAbout #nounNotToPluralise#",
    "teach the locals\nHow to really appreciate\n#deityDomain.capitalize#",
    "warn the world\nAbout #object#",
    "#followerAction#\nAnd #verb#",
    "prostrate yourself\nBefore #nounToPluralise.a#",
    "become #role.a#\nAnd devote your life\nTo #object#",
    "imagine you\nAre #object#",
    "devote your life\nTo #object#",
    "tell me more\nAbout #object#",
    "tell the #role#\nAbout #object#",
    "obey the #role#\nOf #nounToPluralise.s#",
    "humiliate yourself\nFor the sake of #object#",
    "kiss\nThe most #adjective# #role#\nIn #deityPlace#",
    "live the rest of your life\nAs the lowliest #role#\nIn #deityPlace#",
    "make your way directly\nTo #dwelling.a#\n#deityPlace.capitalize#",
    "prostrate yourself\nBefore #dwelling.a#\n#deityPlace.capitalize#",
    "sacrifice your #anyNoun#\nTo #object#",
    "soil yourself\nWith #object#",
    "befoul yourself\nBefore a statue of #object#",
    "change a lightbulb",
    "#pilgrimage#",
    "#pilgrimage#",
    "#pilgrimage#",
    "#pilgrimage#",
    "#pilgrimage#",
    "#pilgrimage#",
    "#pilgrimage#"
    // "become the #adjective# promoter of",
    // "save the #spiritAnimal.s#. And also save",
  ],
  meditation: ["Spend #takesTime#\n#meditating.capitalize# #object#"],
  object: [
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "yourself"
  ],
  specifier: [
    "#specifier# #nounToPluralise#'s",
    "#specifier# #nounNotToPluralise#'s",
    "#nounToPluralise.a#'s #adjective#",
    "#nounNotToPluralise#'s #adjective#",
    "the",
    "the",
    "the",
    "your",
    "your #adjective#",
    "your #adjective#",
    "your #relation#'s",
    "your #relation#'s",
    "the #adjective#",
    "the #adjective#",
    "the #relation#'s"
  ],
  relation: [
    "beloved",
    "boss",
    "colleague",
    "conscience",
    "elderly aunt",
    "enemy",
    "familiar",
    "father",
    "instinct",
    "mother",
    "neighbour",
    "paramour",
    "pet",
    "sacred place",
    "secret crush",
    "shrine",
    "spouse",
    "tortoise",
    "totem"
  ]
};
