module.exports = {
  followerAction: [
    "#verb# #object#",
    "#pilgrimage#",
    "#pilgrimage#",
    "#meditation#",
    "#quest#"
  ],
  pilgrimage: [
    "#travelAction# with #deityName#'s #role# to #pilgrimageSite#",
    "#travelAction# to #pilgrimageSite# and #quest#",
    "#travelAction# to #pilgrimageSite#",
    "gather your apostles and form #band.a#"
  ],
  quest: [
    "find #nounToPluralise.a#",
    "capture #bird.a#. Kiss it, cuddle it, and then set it free",
    "devote your life to studying the #academicField# of #deityDomain#",
    "leave your #bodyPart# behind",
    "sacrifice #animal.a#",
    "observe the world #adverb#",
    "spread the good news about #nounNotToPluralise#",
    "teach the locals how to really appreciate #deityDomain#",
    "warn the world about #object#",
    "#followerAction# and #verb#",
    "abase yourself before #nounToPluralise.a#",
    "become #role.a# and devote your life to #object#",
    "imagine you are #object#",
    "devote your life to #object#",
    "tell me more about #object#",
    "tell the #role# about #object#",
    "obey the #role# of #nounToPluralise.s#",
    "humiliate yourself for the sake of #object#",
    "kiss the most #adjective# #role# #deityPlace#",
    "live the rest of your life as the lowliest #role# #deityPlace#",
    "make your way directly to #dwelling.a# #deityPlace#",
    "prostrate yourself before #dwelling.a# #deityPlace#",
    "sacrifice your #anyNoun# to #object#",
    "soil yourself with #object#",
    "befoul yourself before a statue of #object#",
    "change a lightbulb"
    // "become the #adjective# promoter of",
    // "save the #spiritAnimal.s#. And also save",
  ],
  meditation: ["spend #takesTime# #meditationAction# #object#"],
  object: [
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#nounNotToPluralise#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "#specifier# #nounToPluralise.s#",
    "yourself"
  ],
  specifier: [
    "#specifier# #nounToPluralise#'s",
    "#specifier# #nounNotToPluralise#'s",
    "#nounToPluralise.a#'s #adjective#",
    "#nounNotToPluralise#'s #adjective#",
    "the",
    "the",
    "the",
    "your",
    "your #adjective#",
    "your #adjective#",
    "your #relation#'s",
    "your #relation#'s",
    "the #adjective#",
    "the #adjective#",
    "the #relation#'s"
  ],
  relation: [
    "beloved",
    "boss",
    "colleague",
    "conscience",
    "elderly aunt",
    "enemy",
    "familiar",
    "father",
    "instinct",
    "mother",
    "neighbour",
    "pet",
    "sacred place",
    "secret crush",
    "shrine",
    "spouse",
    "tortoise",
    "totem"
  ]
};
