// TODO - more about how deities look and act
module.exports = [
  "We need to talk about \\#deities. #doing#",
  "Wanna know what I just saw #deityFull# do?",
  "Sometimes I suspect that there are more deities than worshippers. Who ever heard of #deityFull#?",
  "Summoning gods can be a dangerous business. Who just summoned #deityFull#",
  "Talk to me about \\#pantheism. #doing#",
  "The gods can sense that you need guidance. #deityFull# is awaiting your call.",
  "There are so many deities out there. Maybe this one's for you? #doing#",
  "To perform obesiance to #deityFull# #followerAction#.",
  "To perform service to #deityFull# #deityRequest# your #anyNoun#.",
  "Those who anger #deityFull# are liable to be #deityPunishment#.",
  "#deityFull# exists purely #reason#.",
  "Those who value #deityDomain# should pledge their soul to #deityName#, for #deityName# is #deityType# of #deityDomain#.",
  "#deityFull# has a spirit animal: #adjective.a# #spiritAnimal#.",
  "GOD-APPEAL: today, #festival#, the #deityType.s.capitalizeAll# Benevolent Fund issue an appeal on behalf of #deityName#, #problemDeity#.",
  "Could you adopt a deity? There are literally millions of gods and godesses out there waiting for a worshipper like you.",
  "In #dwelling.a# #deityPlace#, #deityFull# is #making#.",
  "It is traditional to eat #anyFood# on #festival#, to guarantee the goodwill of #deityFull# over the following year.",
  "The only approved way of #meditationAction# #deityFull# is to #followerAction#. Reply to this tweet if you reckon you're up to that.",
  "To become the #role# of #deityFull# you must first sacrifice #nounToPluralise.a# at the #festival#.",
  "When #meditationAction# #deityFull# you must #clothe# your #bodyPart# in #buildingMaterial# #reason#.",
  "When you are #making#, be sure to spend time #meditationAction# #deityFull# for that way lies #abstract#.",
  "#deityFull# has been trapped in #dwelling.a# for #takesTime#. They were lured there by #name#, #godType# of #domain#, using #nounToPluralise.a#.",
  "#deityFull# lives in #dwelling.a# #deityPlace#. Nearby, #characterName# builds #dwelling.a#.",
  "#deityName# became #deityType# of #deityDomain# after beating #deityTheir# #relative# #name# in #contest.a#.",
  "#historicTime.capitalize#, #deityFull# created #nounToPluralise.a# and called it #adjective.capitalize# #namePart.capitalize#.",
  "Could you ever care for #deityType.a#? For #adjective.a# #deityType# like #deityName#? #deityName# is a respected authority on #deityDomain#.",
  "In the #dwelling# of #deityFull# there's #adjective.a# #nounToPluralise# which signifies #nounNotToPluralise#.",
  "When the World was young, #deityName# introduced humanity to #deityDomain#. This led #adverb# to the discovery of #nounToPluralise.s#.",
  "When you worship #deityName#, you #verb# #deityDomain#. In many ways, you also #deityRequest# #spiritAnimal.s#.",
  '#deityName# (#nationality# for "The #adjective.capitalize# One") is mostly called upon by people who are #verbIng# #deityDomain#, although some call on #deityThem# for help #verbIng# #nounNotToPluralise#.',
  "#deityFull# has a gift of #nounNotToPluralise# for the first follower to celebrate #festival#.",
  "#deityFull# looks like #adjective.a# #animal# dressed in #buildingMaterial#, only a little more #adjective#.",
  "#deityFull# looks like #adjective.a# #famousPerson# made of #buildingMaterial#, but #moreOrLess# #adjective#."
];
