// TODO - more about how deities appear
// TODO - split out reply prompts so that #origin# can be used for initial replies
module.exports = [
  "To perform obesiance to #deityFull# #followerAction#.\n\nReply to this tweet if you wish to abase yourself to #deityName#",
  "To perform service to #deityFull# #deityRequest# your #anyNoun#.\n\nReply to this tweet for additional ways in which you can venerate #deityName#",
  "Those who anger #deityFull# are liable to be #deityPunishment#.\n\nTo find out how to avoid being #deityPunishment#, reply to this tweet.",
  "#deityFull# exists purely #reason#.\n\nReply to this tweet for guidance from #deityName#.",
  "Those who value #deityDomain# should pledge their soul to #deityName#, for #deityName# is #deityType# of #deityDomain#.\n\nReply to this tweet if you wish to become #deityName#'s latest worshipper.",
  "#deityFull# has a spirit animal: #adjective.a# #spiritAnimal#.\n\nIf you would like your own pet #spiritAnimal#, just reply to this tweet. Terms, conditions, and devotional requirements apply.",
  "GOD-APPEAL: today, #festival#, the #deityType.s.capitalizeAll# Benevolent Fund issue an appeal on behalf of #deityName#, #problemDeity#.\n\nReply to this tweet to make a spiritual donation.",
  "Could you adopt a deity? There are literally millions of gods and godesses out there waiting for a worshipper like you.\n\nReply to this tweet to start worshipping #deityFull# today?",
  "In #dwelling.a# #deityPlace#, #deityFull# is #making#.\n\nReply to this tweet if you think you can help.",
  "It is traditional to eat #anyFood# on #festival#, to guarantee the goodwill of #deityFull# over the following year.\n\nReply to this tweet if that sounds tasty and worthwhile.",
  "The only approved way of #meditationAction# #deityFull# is to #followerAction#. Reply to this tweet if you reckon you're up to that.",
  "To become the #role# of #deityFull# you must first sacrifice #nounToPluralise.a# at the #festival#.\n\nReply to this tweet to make the sacrifice.",
  "When #meditationAction# #deityFull# you must #clothe# your #bodyPart# in #buildingMaterial# #reason#.\n\nWant to do that? Just reply...",
  "When you are #making#, be sure to spend time #meditationAction# #deityFull# for that way lies #abstract#.\n\nReply now or be #deityPunishment#.",
  "#deityFull# has been trapped in #dwelling.a# for #takesTime#. They were lured there by #name#, #godType# of #domain#, using #nounToPluralise.a#.\n\nReply to this tweet to somehow release #deityName#.",
  "#deityFull# lives in #dwelling.a# #deityPlace#. Nearby, #characterName# builds #dwelling.a#.\n\nReply to this tweet to visit #deityPlace#.",
  "#deityName# became #deityType# of #deityDomain# after beating #deityTheir# #relative# #name# in #contest.a#.\n\nReply to this tweet to applaud #deityName# for this victory.",
  "#historicTime.capitalize#, #deityFull# created #nounToPluralise.a# and called it #adjective.capitalize# #namePart.capitalize#.\r\rReply to this tweet if that makes any sense to you‽",
  "Could you ever care for #deityType.a#? For #adjective.a# #deityType# like #deityName#? #deityName# is a respected authority on #deityDomain#.\n\nIf you think you could, please reply to this tweet.",
  "In the #dwelling# of #deityFull# there's #adjective.a# #nounToPluralise# which signifies #nounNotToPluralise#.\n\nReply to this tweet if you want to go look at it.",
  "When the World was young, #deityName# introduced humanity to #deityDomain#. This led #adverb# to the discovery of #nounToPluralise.s#.\n\nReply to this tweet to learn more about #deityDomain#.",
  "When you worship #deityName#, you #verb# #deityDomain#. In many ways, you also #deityRequest# #spiritAnimal.s#.\n\nReply to this tweet with your vow of worship.",
  '#deityName# (#nationality# for "The #adjective.capitalize# One") is mostly called upon by people who are #verbIng# #deityDomain#, although some call on #deityThem# for help #verbIng# #nounNotToPluralise#.\r\rReply if you plan on doing either of those.',
  "#deityFull# has a gift of #nounNotToPluralise# for the first follower to celebrate #festival#.\n\nReply to join the party.",
  "#deityFull# looks like #adjective.a# #animal# dressed in #buildingMaterial#, only a little more #adjective#.\n\nReply to worship #deityThem#.",
  "#deityFull# looks like #adjective.a# #famousPerson# made of #buildingMaterial#, but #moreOrLess# #adjective#.\n\nReply to worship #deityThem#."
];
